" Plugins
call pathogen#infect()

" Set physical tools
set cursorline
set number
set smartindent
set t_Co=16

" Set visual tools
set colorcolumn=81
set ruler

" Colors
syntax on
set background=dark
let g:solarized_termtrans = 1
colorscheme solarized
highlight visual ctermfg=13 " Violet

" Change shift/tab values
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=8 " To see when tabs are used

" Keybindings
nmap <F8> :TagbarToggle<CR>

" Filetype specific settings
au BufNewFile,BufRead *.xml*,*.rdf,*.rej call SetupColorColumnNone()
au BufNewFile,BufRead *.java* call SetupColorColumnOneHundred()
au BufNewFile,BufRead *.txt call SetupTxt()
au BufNewFile,BufRead .git/COMMIT_EDITMSG call SetupGitCommit()

function SetupColorColumnNone()
  set colorcolumn=0
endfunction

function SetupColorColumnOneHundred()
  set colorcolumn=101
endfunction

function SetupTxt()
  setlocal spell spelllang=en_us
endfunction

function SetupGitCommit()
  set colorcolumn=73
  set textwidth=73
endfunction
