function HighlightWhitespace()
    " from http://vim.wikia.com/wiki/Highlight_unwanted_spaces
    highlight ExtraWhitespace ctermbg=red guibg=red
    match ExtraWhitespace /\s\+$/
    autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
    autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
    autocmd InsertLeave * match ExtraWhitespace /\s\+$/
    autocmd BufWinLeave * call clearmatches()
endfunction

function SetColorColumn(pos)
    if exists('+colorcolumn')
        execute "set colorcolumn=".a:pos
    endif
endfunction

function SetIndentSpaceLen(len)
    execute "set shiftwidth=".a:len
    execute "set softtabstop=".a:len
    execute "set tabstop=".a:len
endfunction

function SetupGitCommit()
    call SetColorColumn(72)
    set textwidth=72
endfunction

function SetupTxt()
    setlocal spell spelllang=en_us
endfunction

function PluginIndentGuides()
    " TODO: Do not enable if not available.
    "if !exists('IndentGuidesToggle')
    "    return 1
    "endif
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_space_guides = 1
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=0 " base 02
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=0 " base 02
endfunction

function PluginTagbar()
    " TODO: Do not enable if not available.
    autocmd VimEnter * nested :call tagbar#autoopen(1)
    nmap <F8> :TagbarToggle<CR>
endfunction

" Plugins
call pathogen#infect()
call PluginIndentGuides()
call PluginTagbar()

" Set physical tools
set backspace=indent,eol,start " Equivalent to backspace=2.
call SetColorColumn(80)
set cursorline
filetype plugin indent on " Indentation. Alternative: smartindent.
set number
set ruler " Line/column numbers at the bottom.

set expandtab
call SetIndentSpaceLen(4)

" Colors
set t_Co=16 " Number of available terminal colors.
syntax on
set background=dark
let g:solarized_termtrans = 1
colorscheme solarized
highlight visual ctermfg=13 " Violet
call HighlightWhitespace()

" Saved macros
let @d='o// TODO: '
let @g='o// *** *** //BBhi '
let @h="o/79a*o*** o79i*A/ka"

" Filetype specific settings
au BufNewFile,BufRead *.xml*,*.rdf,*.rej call SetColorColumn(0)
au BufNewFile,BufRead *.java* call SetColorColumn(100)
au BufNewFile,BufRead *.css*,*.js*,*.html*,*.md* call SetIndentSpaceLen(2)
au BufNewFile,BufRead *.txt call SetupTxt()
au BufNewFile,BufRead .git/COMMIT_EDITMSG call SetupGitCommit()
