function Vundle() " https://github.com/VundleVim/Vundle.vim
    set nocompatible              " be iMproved, required
    filetype off                  " required

    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin() "call vundle#begin('~/some/path/here')
    Plugin 'VundleVim/Vundle.vim'

    " The following are examples of different formats supported.
    "Plugin 'tpope/vim-fugitive' " github
    "Plugin 'L9' " vim-scripts.org
    "Plugin 'git://git.wincent.com/command-t.git' " not github
    "Plugin 'file:///home/gmarik/path/to/plugin' " local repo
    "Plugin 'ascenator/L9', {'name': 'newL9'} " naming conflicts
    Plugin 'altercation/vim-colors-solarized'
    Plugin 'guns/vim-clojure-static'
    Plugin 'lambdatoast/elm.vim'
    Plugin 'majutsushi/tagbar'
    Plugin 'nathanaelkane/vim-indent-guides'
    Plugin 'tpope/vim-sleuth'

    call vundle#end()
    filetype plugin indent on    " required
    " Brief help
    " :PluginList       - lists configured plugins
    " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
    " :PluginSearch foo - searches for foo; append `!` to refresh local cache
    " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
    "
    " see :h vundle for more details or wiki for FAQ
    " Put your non-Plugin stuff after this line
endfunction

function HighlightWhitespace()
    " from http://vim.wikia.com/wiki/Highlight_unwanted_spaces
    highlight ExtraWhitespace ctermbg=red guibg=red
    match ExtraWhitespace /\s\+$/
    autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
    autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
    autocmd InsertLeave * match ExtraWhitespace /\s\+$/
    autocmd BufWinLeave * call clearmatches()
endfunction

function SetColorColumn(pos)
    if exists('+colorcolumn')
        execute "set colorcolumn=".a:pos
    endif
endfunction

function SetIndentSpaceLen(len)
    execute "set shiftwidth=".a:len
    execute "set softtabstop=".a:len
    execute "set tabstop=".a:len
endfunction

function SetupGitCommit()
    call SetColorColumn(73)
    set textwidth=72
endfunction

function SetupTxt()
    setlocal spell spelllang=en_us
endfunction

function PluginIndentGuides()
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_space_guides = 1
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_auto_colors = 0
    "autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=10 " base 01
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=0 " base 02
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=0 " base 02
endfunction

function PluginTagbar()
    " autocmd VimEnter * nested :call tagbar#autoopen(1)
    nmap <F8> :TagbarToggle<CR>
endfunction

function PluginSolarized()
    let g:solarized_termtrans = 1
    colorscheme solarized
    highlight visual ctermfg=13 " Violet
    "set t_Co=16 " available terminal colors - enable if bold
endfunction


" MAIN START
call Vundle()
call PluginTagbar()

" Colors
syntax on
set background=dark
call PluginSolarized()
call HighlightWhitespace()

" Set physical tools
call SetColorColumn(80)
set backspace=indent,eol,start " Equivalent to backspace=2.
set cursorline
set hlsearch " Highlight search results.
set number " Enables current line number in relativenumber
set relativenumber
set ruler " Line/column numbers at the bottom.
set smartcase
set wildmenu

set expandtab
"call SetIndentSpaceLen(4)

set splitbelow " More natural splits.
set splitright

" Remap
command Qa qa
command W w
command Wq wq
map <Leader>c :set ignorecase!<CR>
map <Leader>h :set hlsearch!<CR>
map <Leader>p :set paste!<CR>

" Saved macros
let @d='o// TODO: '
let @g='o// *** *** //BBhi '
let @h="o/79a*o*** o79i*A/ka"
let @l="oLog.d(\"lol\", \"\");2hi"

" Filetype specific settings
au BufNewFile,BufRead *.xml*,*.rdf,*.rej call SetColorColumn(0)
au BufNewFile,BufRead *.java* call SetColorColumn(99)
au BufNewFile,BufRead *.jsm* set filetype=javascript
au BufNewFile,BufRead *.md set textwidth=79
au BufNewFile,BufRead *.md set filetype=markdown
"au BufNewFile,BufRead *.coffee*,*.css*,*.js*,*.html* call SetIndentSpaceLen(2)
au BufNewFile,BufRead *.txt call SetupTxt()
au BufNewFile,BufRead .git/COMMIT_EDITMSG call SetupGitCommit()

au Filetype html,xml,xsl source ~/.vim/scripts/closetag.vim/plugin/closetag.vim
