# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1500
SAVEHIST=1500
setopt appendhistory

unsetopt autocd beep

bindkey -v

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/mcomella/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Use dircolors (if it exists)
which dircolors &> /dev/null && if [ -f $HOME/.dircolors ]; then
    eval `dircolors $HOME/.dircolors`
fi

# Setting umask
umask 007

# Update default editor
export EDITOR=vim
export VISUAL=vim

# Prompt
export PS1=$'%U%n%F{4}@%m%f%u:%2~$ '

# Aliases
if [ -f $HOME/.zsh_aliases ]; then
  . $HOME/.zsh_aliases
fi

# Local config
if [ -f $HOME/.zshrc_local ]; then
  . $HOME/.zshrc_local
fi
